//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AcademicActivityClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type SearchAcademicActivitiesAcademicActivityQueryParameters = {
  curriculumId?: number | undefined ;
}

export function searchAcademicActivitiesUrl(curriculumId?: number | undefined): string {
  let url_ = getBaseUrl() + "/academic-activity?";
if (curriculumId === null)
    throw new Error("The parameter 'curriculumId' cannot be null.");
else if (curriculumId !== undefined)
    url_ += "curriculumId=" + encodeURIComponent("" + curriculumId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let searchAcademicActivitiesDefaultOptions: Omit<UseQueryOptions<Types.AcademicActivityDto[], unknown, Types.AcademicActivityDto[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.AcademicActivityDto[], unknown, Types.AcademicActivityDto[]>, 'queryFn'>> = {
};
export function getSearchAcademicActivitiesDefaultOptions() {
  return searchAcademicActivitiesDefaultOptions;
};
export function setSearchAcademicActivitiesDefaultOptions(options: typeof searchAcademicActivitiesDefaultOptions) {
  searchAcademicActivitiesDefaultOptions = options;
}

export function searchAcademicActivitiesQueryKey(curriculumId?: number | undefined): QueryKey;
export function searchAcademicActivitiesQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { curriculumId,  } = params[0] as SearchAcademicActivitiesAcademicActivityQueryParameters;

    return trimArrayEnd([
        'AcademicActivityClient',
        'searchAcademicActivities',
        curriculumId as any,
      ]);
  } else {
    return trimArrayEnd([
        'AcademicActivityClient',
        'searchAcademicActivities',
        ...params
      ]);
  }
}
export function __searchAcademicActivities(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.searchAcademicActivities(
      context.queryKey[2] as number | undefined,axiosConfig    );
}

export function useSearchAcademicActivitiesQuery<TSelectData = Types.AcademicActivityDto[], TError = unknown>(dto: SearchAcademicActivitiesAcademicActivityQueryParameters, options?: Omit<UseQueryOptions<Types.AcademicActivityDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useSearchAcademicActivitiesQuery<TSelectData = Types.AcademicActivityDto[], TError = unknown>(curriculumId?: number | undefined, options?: Omit<UseQueryOptions<Types.AcademicActivityDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useSearchAcademicActivitiesQuery<TSelectData = Types.AcademicActivityDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.AcademicActivityDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let curriculumId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ curriculumId,  } = params[0] as SearchAcademicActivitiesAcademicActivityQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [curriculumId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.AcademicActivityDto[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __searchAcademicActivities(context, axiosConfig) : __searchAcademicActivities,
    queryKey: searchAcademicActivitiesQueryKey(curriculumId),
    ...searchAcademicActivitiesDefaultOptions as unknown as Omit<UseQueryOptions<Types.AcademicActivityDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setSearchAcademicActivitiesData(queryClient: QueryClient, updater: (data: Types.AcademicActivityDto[] | undefined) => Types.AcademicActivityDto[], curriculumId?: number | undefined) {
  queryClient.setQueryData(searchAcademicActivitiesQueryKey(curriculumId),
    updater
  );
}

export function setSearchAcademicActivitiesDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.AcademicActivityDto[] | undefined) => Types.AcademicActivityDto[]) {
  queryClient.setQueryData(queryKey, updater);
}