//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type {
  UseQueryResult,
  QueryFunctionContext,
  UseQueryOptions,
  QueryClient,
  QueryKey,
  MutationKey,
  UseMutationOptions,
  UseMutationResult,
  QueryMeta,
  MutationMeta,
} from '@tanstack/react-query';
import {
  trimArrayEnd,
  isParameterObject,
  getBaseUrl,
  addMetaToOptions,
} from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AtomInSemesterClient';
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type CreateAtomInSemesterAtomInSemesterQueryParameters = {
  atomId: number;
  semesterId: number;
};

export type DeleteAtomInSemesterAtomInSemesterQueryParameters = {
  atomId: number;
  semesterId: number;
};

export type SetAtomCreditAtomInSemesterQueryParameters = {
  atomId: number;
  semesterId: number;
};

export function createAtomInSemesterUrl(
  atomId: number,
  semesterId: number,
): string {
  let url_ = getBaseUrl() + '/api/atom/{atomId}/semester/{semesterId}';
  if (atomId === undefined || atomId === null)
    throw new Error("The parameter 'atomId' must be defined.");
  url_ = url_.replace('{atomId}', encodeURIComponent('' + atomId));
  if (semesterId === undefined || semesterId === null)
    throw new Error("The parameter 'semesterId' must be defined.");
  url_ = url_.replace('{semesterId}', encodeURIComponent('' + semesterId));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function createAtomInSemesterMutationKey(
  atomId: number,
  semesterId: number,
): MutationKey {
  return trimArrayEnd([
    'AtomInSemesterClient',
    'createAtomInSemester',
    atomId as any,
    semesterId as any,
  ]);
}

export function useCreateAtomInSemesterMutation<TContext>(
  atomId: number,
  semesterId: number,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = createAtomInSemesterMutationKey(atomId, semesterId);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.createAtomInSemester(atomId, semesterId),
    mutationKey: key,
  });
}

type CreateAtomInSemester__MutationParameters =
  CreateAtomInSemesterAtomInSemesterQueryParameters;

export function useCreateAtomInSemesterMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      CreateAtomInSemester__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: CreateAtomInSemesterAtomInSemesterQueryParameters },
): UseMutationResult<
  void,
  unknown,
  CreateAtomInSemester__MutationParameters,
  TContext
> {
  const key = createAtomInSemesterMutationKey(
    options?.parameters?.atomId!,
    options?.parameters?.semesterId!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: CreateAtomInSemester__MutationParameters) =>
      Client.createAtomInSemester(
        data.atomId ?? options?.parameters?.atomId!,
        data.semesterId ?? options?.parameters?.semesterId!,
      ),
    mutationKey: key,
  });
}

export function deleteAtomInSemesterUrl(
  atomId: number,
  semesterId: number,
): string {
  let url_ = getBaseUrl() + '/api/atom/{atomId}/semester/{semesterId}';
  if (atomId === undefined || atomId === null)
    throw new Error("The parameter 'atomId' must be defined.");
  url_ = url_.replace('{atomId}', encodeURIComponent('' + atomId));
  if (semesterId === undefined || semesterId === null)
    throw new Error("The parameter 'semesterId' must be defined.");
  url_ = url_.replace('{semesterId}', encodeURIComponent('' + semesterId));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function deleteAtomInSemesterMutationKey(
  atomId: number,
  semesterId: number,
): MutationKey {
  return trimArrayEnd([
    'AtomInSemesterClient',
    'deleteAtomInSemester',
    atomId as any,
    semesterId as any,
  ]);
}

export function useDeleteAtomInSemesterMutation<TContext>(
  atomId: number,
  semesterId: number,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteAtomInSemesterMutationKey(atomId, semesterId);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.deleteAtomInSemester(atomId, semesterId),
    mutationKey: key,
  });
}

type DeleteAtomInSemester__MutationParameters =
  DeleteAtomInSemesterAtomInSemesterQueryParameters;

export function useDeleteAtomInSemesterMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      DeleteAtomInSemester__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: DeleteAtomInSemesterAtomInSemesterQueryParameters },
): UseMutationResult<
  void,
  unknown,
  DeleteAtomInSemester__MutationParameters,
  TContext
> {
  const key = deleteAtomInSemesterMutationKey(
    options?.parameters?.atomId!,
    options?.parameters?.semesterId!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: DeleteAtomInSemester__MutationParameters) =>
      Client.deleteAtomInSemester(
        data.atomId ?? options?.parameters?.atomId!,
        data.semesterId ?? options?.parameters?.semesterId!,
      ),
    mutationKey: key,
  });
}

export function setAtomCreditUrl(atomId: number, semesterId: number): string {
  let url_ = getBaseUrl() + '/api/atom/{atomId}/semester/{semesterId}/credit';
  if (atomId === undefined || atomId === null)
    throw new Error("The parameter 'atomId' must be defined.");
  url_ = url_.replace('{atomId}', encodeURIComponent('' + atomId));
  if (semesterId === undefined || semesterId === null)
    throw new Error("The parameter 'semesterId' must be defined.");
  url_ = url_.replace('{semesterId}', encodeURIComponent('' + semesterId));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function setAtomCreditMutationKey(
  atomId: number,
  semesterId: number,
): MutationKey {
  return trimArrayEnd([
    'AtomInSemesterClient',
    'setAtomCredit',
    atomId as any,
    semesterId as any,
  ]);
}

export function useSetAtomCreditMutation<TContext>(
  atomId: number,
  semesterId: number,
  options?: Omit<
    UseMutationOptions<void, unknown, Types.SetAtomCreditDto, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, Types.SetAtomCreditDto, TContext> {
  const key = setAtomCreditMutationKey(atomId, semesterId);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (dto: Types.SetAtomCreditDto) =>
      Client.setAtomCredit(atomId, semesterId, dto),
    mutationKey: key,
  });
}

type SetAtomCredit__MutationParameters =
  SetAtomCreditAtomInSemesterQueryParameters & {
    dto: Types.SetAtomCreditDto;
  };

export function useSetAtomCreditMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      SetAtomCredit__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: SetAtomCreditAtomInSemesterQueryParameters },
): UseMutationResult<
  void,
  unknown,
  SetAtomCredit__MutationParameters,
  TContext
> {
  const key = setAtomCreditMutationKey(
    options?.parameters?.atomId!,
    options?.parameters?.semesterId!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: SetAtomCredit__MutationParameters) =>
      Client.setAtomCredit(
        data.atomId ?? options?.parameters?.atomId!,
        data.semesterId ?? options?.parameters?.semesterId!,
        data.dto,
      ),
    mutationKey: key,
  });
}
