//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AtomClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type UpdateAtomAtomQueryParameters = {
  id: number ;
}

export type DeleteAtomAtomQueryParameters = {
  id: number ;
}

export function createAtomUrl(): string {
  let url_ = getBaseUrl() + "/atom";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createAtomMutationKey(): MutationKey {
  return trimArrayEnd([
      'AtomClient',
      'createAtom',
    ]);
}

export function useCreateAtomMutation<TContext>(options?: Omit<UseMutationOptions<number, unknown, Types.CreateAtomDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<number, unknown, Types.CreateAtomDto, TContext> {
  const key = createAtomMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (createAtomDto: Types.CreateAtomDto) => Client.createAtom(createAtomDto),
    mutationKey: key,
  });
}
  
export function updateAtomUrl(id: number): string {
  let url_ = getBaseUrl() + "/atom/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateAtomMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AtomClient',
      'updateAtom',
      id as any,
    ]);
}

export function useUpdateAtomMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, Types.UpdateAtomDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.UpdateAtomDto, TContext> {
  const key = updateAtomMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (updateAtomDto: Types.UpdateAtomDto) => Client.updateAtom(id, updateAtomDto),
    mutationKey: key,
  });
}
  
type UpdateAtom__MutationParameters = UpdateAtomAtomQueryParameters & {
  updateAtomDto: Types.UpdateAtomDto;
}

export function useUpdateAtomMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, UpdateAtom__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: UpdateAtomAtomQueryParameters}): UseMutationResult<void, unknown, UpdateAtom__MutationParameters, TContext> {
  const key = updateAtomMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: UpdateAtom__MutationParameters) => Client.updateAtom(data.id ?? options?.parameters?.id!, data.updateAtomDto),
  mutationKey: key,
});
}
  
export function deleteAtomUrl(id: number): string {
  let url_ = getBaseUrl() + "/atom/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteAtomMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AtomClient',
      'deleteAtom',
      id as any,
    ]);
}

export function useDeleteAtomMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteAtomMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteAtom(id),
    mutationKey: key,
  });
}
  
type DeleteAtom__MutationParameters = DeleteAtomAtomQueryParameters

export function useDeleteAtomMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteAtom__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteAtomAtomQueryParameters}): UseMutationResult<void, unknown, DeleteAtom__MutationParameters, TContext> {
  const key = deleteAtomMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteAtom__MutationParameters) => Client.deleteAtom(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}