//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function createAtom(createAtomDto: Types.CreateAtomDto, config?: AxiosRequestConfig | undefined): Promise<number> {
    let url_ = getBaseUrl() + "/atom";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateAtomDto(createAtomDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreateAtom,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreateAtom?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreateAtom(_response);
    });
}

function processCreateAtom(response: AxiosResponse): Promise<number> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
    
        result200 = resultData200;
    
        return Promise.resolve<number>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<number>(null as any);
}

export function updateAtom(atomId: number, updateAtomDto: Types.UpdateAtomDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/atom/{atomId}";
    if (atomId === undefined || atomId === null)
      throw new Error("The parameter 'atomId' must be defined.");
    url_ = url_.replace("{atomId}", encodeURIComponent("" + atomId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdateAtomDto(updateAtomDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdateAtom,
        ...config,
        data: content_,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigUpdateAtom?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdateAtom(_response);
    });
}

function processUpdateAtom(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function deleteAtom(atomId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/atom/{atomId}";
    if (atomId === undefined || atomId === null)
      throw new Error("The parameter 'atomId' must be defined.");
    url_ = url_.replace("{atomId}", encodeURIComponent("" + atomId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeleteAtom,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeleteAtom?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeleteAtom(_response);
    });
}

function processDeleteAtom(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Get atoms of a curriculum
 * @param hasNoParentModule (optional) If true, returns atoms without parents. Else, returns all atoms
 */
export function getAtomsByCurriculum(curriculumId: number, hasNoParentModule?: boolean | undefined, config?: AxiosRequestConfig | undefined): Promise<Types.AtomDto[]> {
    let url_ = getBaseUrl() + "/atom/curriculum/{curriculumId}?";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
    if (hasNoParentModule === null)
        throw new Error("The parameter 'hasNoParentModule' cannot be null.");
    else if (hasNoParentModule !== undefined)
        url_ += "hasNoParentModule=" + encodeURIComponent("" + hasNoParentModule) + "&";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetAtomsByCurriculum,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetAtomsByCurriculum?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetAtomsByCurriculum(_response);
    });
}

function processGetAtomsByCurriculum(response: AxiosResponse): Promise<Types.AtomDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initAtomDto(item)
              );
            }
        return Promise.resolve<Types.AtomDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.AtomDto[]>(null as any);
}
let _requestConfigCreateAtom: Partial<AxiosRequestConfig> | null;
export function getCreateAtomRequestConfig() {
  return _requestConfigCreateAtom;
}
export function setCreateAtomRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreateAtom = value;
}
export function patchCreateAtomRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreateAtom = patch(_requestConfigCreateAtom ?? {});
}

let _requestConfigUpdateAtom: Partial<AxiosRequestConfig> | null;
export function getUpdateAtomRequestConfig() {
  return _requestConfigUpdateAtom;
}
export function setUpdateAtomRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdateAtom = value;
}
export function patchUpdateAtomRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdateAtom = patch(_requestConfigUpdateAtom ?? {});
}

let _requestConfigDeleteAtom: Partial<AxiosRequestConfig> | null;
export function getDeleteAtomRequestConfig() {
  return _requestConfigDeleteAtom;
}
export function setDeleteAtomRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeleteAtom = value;
}
export function patchDeleteAtomRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeleteAtom = patch(_requestConfigDeleteAtom ?? {});
}

let _requestConfigGetAtomsByCurriculum: Partial<AxiosRequestConfig> | null;
export function getGetAtomsByCurriculumRequestConfig() {
  return _requestConfigGetAtomsByCurriculum;
}
export function setGetAtomsByCurriculumRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetAtomsByCurriculum = value;
}
export function patchGetAtomsByCurriculumRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetAtomsByCurriculum = patch(_requestConfigGetAtomsByCurriculum ?? {});
}