//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import { AttestationClient as AttestationClientClass } from '../axios-client';
import { createClient, getClientFactory } from './helpers';

export const Client = () => getClientFactory()(AttestationClientClass);
import type { AxiosRequestConfig } from 'axios';

export function searchAttestationsUrl(): string {
  let url_ = getBaseUrl() + "/attestation";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let searchAttestationsDefaultOptions: Omit<UseQueryOptions<Types.AttestationDto[], unknown, Types.AttestationDto[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.AttestationDto[], unknown, Types.AttestationDto[]>, 'queryFn'>> = {
};
export function getSearchAttestationsDefaultOptions() {
  return searchAttestationsDefaultOptions;
};
export function setSearchAttestationsDefaultOptions(options: typeof searchAttestationsDefaultOptions) {
  searchAttestationsDefaultOptions = options;
}

export function searchAttestationsQueryKey(): QueryKey;
export function searchAttestationsQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'AttestationClient',
      'searchAttestations',
    ]);
}
export function __searchAttestations(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client().searchAttestations(
);
}

export function useSearchAttestationsQuery<TSelectData = Types.AttestationDto[], TError = unknown>(options?: Omit<UseQueryOptions<Types.AttestationDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useSearchAttestationsQuery<TSelectData = Types.AttestationDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.AttestationDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.AttestationDto[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __searchAttestations(context, axiosConfig) : __searchAttestations,
    queryKey: searchAttestationsQueryKey(),
    ...searchAttestationsDefaultOptions as unknown as Omit<UseQueryOptions<Types.AttestationDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setSearchAttestationsData(queryClient: QueryClient, updater: (data: Types.AttestationDto[] | undefined) => Types.AttestationDto[], ) {
  queryClient.setQueryData(searchAttestationsQueryKey(),
    updater
  );
}

export function setSearchAttestationsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.AttestationDto[] | undefined) => Types.AttestationDto[]) {
  queryClient.setQueryData(queryKey, updater);
}