//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AuthClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';



export function registerUrl(): string {
  let url_ = getBaseUrl() + "/api/auth/register";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function registerMutationKey(): MutationKey {
  return trimArrayEnd([
      'AuthClient',
      'register',
    ]);
}

export function useRegisterMutation<TContext>(options?: Omit<UseMutationOptions<Types.TokenDto, unknown, Types.RegisterDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TokenDto, unknown, Types.RegisterDto, TContext> {
  const key = registerMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (registerDto: Types.RegisterDto) => Client.register(registerDto),
    mutationKey: key,
  });
}
  
export function loginUrl(): string {
  let url_ = getBaseUrl() + "/api/auth/login";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function loginMutationKey(): MutationKey {
  return trimArrayEnd([
      'AuthClient',
      'login',
    ]);
}

export function useLoginMutation<TContext>(options?: Omit<UseMutationOptions<Types.TokenDto, unknown, Types.LoginDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TokenDto, unknown, Types.LoginDto, TContext> {
  const key = loginMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (loginDto: Types.LoginDto) => Client.login(loginDto),
    mutationKey: key,
  });
}
  
export function refreshUrl(): string {
  let url_ = getBaseUrl() + "/api/auth/refresh";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function refreshMutationKey(): MutationKey {
  return trimArrayEnd([
      'AuthClient',
      'refresh',
    ]);
}

export function useRefreshMutation<TContext>(options?: Omit<UseMutationOptions<Types.TokenDto, unknown, Types.TokenDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TokenDto, unknown, Types.TokenDto, TContext> {
  const key = refreshMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (tokenDto: Types.TokenDto) => Client.refresh(tokenDto),
    mutationKey: key,
  });
}
  
export function logoutUrl(): string {
  let url_ = getBaseUrl() + "/api/auth/logout";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function logoutMutationKey(): MutationKey {
  return trimArrayEnd([
      'AuthClient',
      'logout',
    ]);
}

export function useLogoutMutation<TContext>(options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = logoutMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.logout(),
    mutationKey: key,
  });
}
  
export function changePasswordUrl(): string {
  let url_ = getBaseUrl() + "/api/auth/change-password";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function changePasswordMutationKey(): MutationKey {
  return trimArrayEnd([
      'AuthClient',
      'changePassword',
    ]);
}

export function useChangePasswordMutation<TContext>(options?: Omit<UseMutationOptions<void, unknown, Types.ChangePasswordDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.ChangePasswordDto, TContext> {
  const key = changePasswordMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (changePasswordDto: Types.ChangePasswordDto) => Client.changePassword(changePasswordDto),
    mutationKey: key,
  });
}