//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function getIndexes(curriculumId: number, config?: AxiosRequestConfig | undefined): Promise<Types.TupleOfIntegerAndString[]> {
    let url_ = getBaseUrl() + "/api/component/index/{curriculumId}";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetIndexes,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetIndexes?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetIndexes(_response);
    });
}

function processGetIndexes(response: AxiosResponse): Promise<Types.TupleOfIntegerAndString[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initTupleOfIntegerAndString(item)
              );
            }
        return Promise.resolve<Types.TupleOfIntegerAndString[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.TupleOfIntegerAndString[]>(null as any);
}
let _requestConfigGetIndexes: Partial<AxiosRequestConfig> | null;
export function getGetIndexesRequestConfig() {
  return _requestConfigGetIndexes;
}
export function setGetIndexesRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetIndexes = value;
}
export function patchGetIndexesRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetIndexes = patch(_requestConfigGetIndexes ?? {});
}