//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function getCompetences(curriculumId: number, config?: AxiosRequestConfig | undefined): Promise<Types.CompetenceDto[]> {
    let url_ = getBaseUrl() + "/competence/{curriculumId}";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetCompetences,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetCompetences?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetCompetences(_response);
    });
}

function processGetCompetences(response: AxiosResponse): Promise<Types.CompetenceDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initCompetenceDto(item)
              );
            }
        return Promise.resolve<Types.CompetenceDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.CompetenceDto[]>(null as any);
}

export function createCompetence(curriculumId: number, createCompetenceDto: Types.CreateCompetenceDto, config?: AxiosRequestConfig | undefined): Promise<Types.CompetenceDto> {
    let url_ = getBaseUrl() + "/competence/{curriculumId}";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateCompetenceDto(createCompetenceDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreateCompetence,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreateCompetence?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreateCompetence(_response);
    });
}

function processCreateCompetence(response: AxiosResponse): Promise<Types.CompetenceDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initCompetenceDto(resultData200);
        return Promise.resolve<Types.CompetenceDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.CompetenceDto>(null as any);
}

export function updateCompetence(competenceId: number, updateCompetenceDto: Types.UpdateCompetenceDto, config?: AxiosRequestConfig | undefined): Promise<Types.CompetenceDto> {
    let url_ = getBaseUrl() + "/competence/{competenceId}";
    if (competenceId === undefined || competenceId === null)
      throw new Error("The parameter 'competenceId' must be defined.");
    url_ = url_.replace("{competenceId}", encodeURIComponent("" + competenceId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdateCompetenceDto(updateCompetenceDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdateCompetence,
        ...config,
        data: content_,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigUpdateCompetence?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdateCompetence(_response);
    });
}

function processUpdateCompetence(response: AxiosResponse): Promise<Types.CompetenceDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initCompetenceDto(resultData200);
        return Promise.resolve<Types.CompetenceDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.CompetenceDto>(null as any);
}

export function deleteCompetence(competenceId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/competence/{competenceId}";
    if (competenceId === undefined || competenceId === null)
      throw new Error("The parameter 'competenceId' must be defined.");
    url_ = url_.replace("{competenceId}", encodeURIComponent("" + competenceId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeleteCompetence,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeleteCompetence?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeleteCompetence(_response);
    });
}

function processDeleteCompetence(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function createIndicator(competenceId: number, createIndicatorDto: Types.CreateCompetenceIndicatorDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/competence/{competenceId}/indicator";
    if (competenceId === undefined || competenceId === null)
      throw new Error("The parameter 'competenceId' must be defined.");
    url_ = url_.replace("{competenceId}", encodeURIComponent("" + competenceId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateCompetenceIndicatorDto(createIndicatorDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreateIndicator,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreateIndicator?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreateIndicator(_response);
    });
}

function processCreateIndicator(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function updateIndicator(indicatorId: number, updateIndicatorDto: Types.UpdateCompetenceIndicatorDto, competenceId: string, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/competence/{competenceId}/indicator/{indicatorId}";
    if (indicatorId === undefined || indicatorId === null)
      throw new Error("The parameter 'indicatorId' must be defined.");
    url_ = url_.replace("{indicatorId}", encodeURIComponent("" + indicatorId));
    if (competenceId === undefined || competenceId === null)
      throw new Error("The parameter 'competenceId' must be defined.");
    url_ = url_.replace("{competenceId}", encodeURIComponent("" + competenceId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdateCompetenceIndicatorDto(updateIndicatorDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdateIndicator,
        ...config,
        data: content_,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigUpdateIndicator?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdateIndicator(_response);
    });
}

function processUpdateIndicator(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function deleteIndicator(indicatorId: number, competenceId: string, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/competence/{competenceId}/indicator/{indicatorId}";
    if (indicatorId === undefined || indicatorId === null)
      throw new Error("The parameter 'indicatorId' must be defined.");
    url_ = url_.replace("{indicatorId}", encodeURIComponent("" + indicatorId));
    if (competenceId === undefined || competenceId === null)
      throw new Error("The parameter 'competenceId' must be defined.");
    url_ = url_.replace("{competenceId}", encodeURIComponent("" + competenceId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeleteIndicator,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeleteIndicator?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeleteIndicator(_response);
    });
}

function processDeleteIndicator(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigGetCompetences: Partial<AxiosRequestConfig> | null;
export function getGetCompetencesRequestConfig() {
  return _requestConfigGetCompetences;
}
export function setGetCompetencesRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetCompetences = value;
}
export function patchGetCompetencesRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetCompetences = patch(_requestConfigGetCompetences ?? {});
}

let _requestConfigCreateCompetence: Partial<AxiosRequestConfig> | null;
export function getCreateCompetenceRequestConfig() {
  return _requestConfigCreateCompetence;
}
export function setCreateCompetenceRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreateCompetence = value;
}
export function patchCreateCompetenceRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreateCompetence = patch(_requestConfigCreateCompetence ?? {});
}

let _requestConfigUpdateCompetence: Partial<AxiosRequestConfig> | null;
export function getUpdateCompetenceRequestConfig() {
  return _requestConfigUpdateCompetence;
}
export function setUpdateCompetenceRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdateCompetence = value;
}
export function patchUpdateCompetenceRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdateCompetence = patch(_requestConfigUpdateCompetence ?? {});
}

let _requestConfigDeleteCompetence: Partial<AxiosRequestConfig> | null;
export function getDeleteCompetenceRequestConfig() {
  return _requestConfigDeleteCompetence;
}
export function setDeleteCompetenceRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeleteCompetence = value;
}
export function patchDeleteCompetenceRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeleteCompetence = patch(_requestConfigDeleteCompetence ?? {});
}

let _requestConfigCreateIndicator: Partial<AxiosRequestConfig> | null;
export function getCreateIndicatorRequestConfig() {
  return _requestConfigCreateIndicator;
}
export function setCreateIndicatorRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreateIndicator = value;
}
export function patchCreateIndicatorRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreateIndicator = patch(_requestConfigCreateIndicator ?? {});
}

let _requestConfigUpdateIndicator: Partial<AxiosRequestConfig> | null;
export function getUpdateIndicatorRequestConfig() {
  return _requestConfigUpdateIndicator;
}
export function setUpdateIndicatorRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdateIndicator = value;
}
export function patchUpdateIndicatorRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdateIndicator = patch(_requestConfigUpdateIndicator ?? {});
}

let _requestConfigDeleteIndicator: Partial<AxiosRequestConfig> | null;
export function getDeleteIndicatorRequestConfig() {
  return _requestConfigDeleteIndicator;
}
export function setDeleteIndicatorRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeleteIndicator = value;
}
export function patchDeleteIndicatorRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeleteIndicator = patch(_requestConfigDeleteIndicator ?? {});
}