//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import { CurriculumClient as CurriculumClientClass } from '../axios-client';
import { createClient, getClientFactory } from './helpers';

export const Client = () => getClientFactory()(CurriculumClientClass);
import type { AxiosRequestConfig } from 'axios';


export type GetCurriculumCurriculumQueryParameters = {
  id: number ;
}

export function createCurriculumUrl(): string {
  let url_ = getBaseUrl() + "/curriculum";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createCurriculumMutationKey(): MutationKey {
  return trimArrayEnd([
      'CurriculumClient',
      'createCurriculum',
    ]);
}

export function useCreateCurriculumMutation<TContext>(options?: Omit<UseMutationOptions<number, unknown, Types.CreateCurriculumDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<number, unknown, Types.CreateCurriculumDto, TContext> {
  const key = createCurriculumMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (createCurriculumDto: Types.CreateCurriculumDto) => Client().createCurriculum(createCurriculumDto),
    mutationKey: key,
  });
}
  
export function searchCurriculumsUrl(): string {
  let url_ = getBaseUrl() + "/curriculum";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let searchCurriculumsDefaultOptions: Omit<UseQueryOptions<Types.CurriculumShortDto[], unknown, Types.CurriculumShortDto[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CurriculumShortDto[], unknown, Types.CurriculumShortDto[]>, 'queryFn'>> = {
};
export function getSearchCurriculumsDefaultOptions() {
  return searchCurriculumsDefaultOptions;
};
export function setSearchCurriculumsDefaultOptions(options: typeof searchCurriculumsDefaultOptions) {
  searchCurriculumsDefaultOptions = options;
}

export function searchCurriculumsQueryKey(): QueryKey;
export function searchCurriculumsQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'CurriculumClient',
      'searchCurriculums',
    ]);
}
export function __searchCurriculums(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client().searchCurriculums(
);
}

export function useSearchCurriculumsQuery<TSelectData = Types.CurriculumShortDto[], TError = unknown>(options?: Omit<UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useSearchCurriculumsQuery<TSelectData = Types.CurriculumShortDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CurriculumShortDto[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __searchCurriculums(context, axiosConfig) : __searchCurriculums,
    queryKey: searchCurriculumsQueryKey(),
    ...searchCurriculumsDefaultOptions as unknown as Omit<UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setSearchCurriculumsData(queryClient: QueryClient, updater: (data: Types.CurriculumShortDto[] | undefined) => Types.CurriculumShortDto[], ) {
  queryClient.setQueryData(searchCurriculumsQueryKey(),
    updater
  );
}

export function setSearchCurriculumsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CurriculumShortDto[] | undefined) => Types.CurriculumShortDto[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function getCurriculumUrl(id: number): string {
  let url_ = getBaseUrl() + "/curriculum/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getCurriculumDefaultOptions: Omit<UseQueryOptions<Types.CurriculumDto, unknown, Types.CurriculumDto>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CurriculumDto, unknown, Types.CurriculumDto>, 'queryFn'>> = {
};
export function getGetCurriculumDefaultOptions() {
  return getCurriculumDefaultOptions;
};
export function setGetCurriculumDefaultOptions(options: typeof getCurriculumDefaultOptions) {
  getCurriculumDefaultOptions = options;
}

export function getCurriculumQueryKey(id: number): QueryKey;
export function getCurriculumQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetCurriculumCurriculumQueryParameters;

    return trimArrayEnd([
        'CurriculumClient',
        'getCurriculum',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'CurriculumClient',
        'getCurriculum',
        ...params
      ]);
  }
}
export function __getCurriculum(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client().getCurriculum(
      context.queryKey[2] as number);
}

export function useGetCurriculumQuery<TSelectData = Types.CurriculumDto, TError = unknown>(dto: GetCurriculumCurriculumQueryParameters, options?: Omit<UseQueryOptions<Types.CurriculumDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetCurriculumQuery<TSelectData = Types.CurriculumDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.CurriculumDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetCurriculumQuery<TSelectData = Types.CurriculumDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CurriculumDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetCurriculumCurriculumQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CurriculumDto, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getCurriculum(context, axiosConfig) : __getCurriculum,
    queryKey: getCurriculumQueryKey(id),
    ...getCurriculumDefaultOptions as unknown as Omit<UseQueryOptions<Types.CurriculumDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetCurriculumData(queryClient: QueryClient, updater: (data: Types.CurriculumDto | undefined) => Types.CurriculumDto, id: number) {
  queryClient.setQueryData(getCurriculumQueryKey(id),
    updater
  );
}

export function setGetCurriculumDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CurriculumDto | undefined) => Types.CurriculumDto) {
  queryClient.setQueryData(queryKey, updater);
}