//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type {
  UseQueryResult,
  QueryFunctionContext,
  UseQueryOptions,
  QueryClient,
  QueryKey,
  MutationKey,
  UseMutationOptions,
  UseMutationResult,
  QueryMeta,
  MutationMeta,
} from '@tanstack/react-query';
import {
  trimArrayEnd,
  isParameterObject,
  getBaseUrl,
  addMetaToOptions,
} from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './CurriculumClient';
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type UpdateCurriculumCurriculumQueryParameters = {
  id: number;
};

export type GetCurriculumCurriculumQueryParameters = {
  id: number;
};

export type DeleteCurriculumCurriculumQueryParameters = {
  id: number;
};

export type SetCurriculumSettingsCurriculumQueryParameters = {
  id: number;
};

export type GetUserPermissionsForCurriculumByIdCurriculumQueryParameters = {
  id: number;
};

export type ConnectCurriculumWithDivisionCurriculumQueryParameters = {
  id: number;
  curriculumId?: number | undefined;
};

export type GetUserPermissionsForCurriculumByIdCurriculumQueryParameters = {
  id: number ;
}

export type ConnectCurriculumWithDivisionCurriculumQueryParameters = {
  id: number ;
  curriculumId?: number | undefined ;
}

export function createCurriculumUrl(): string {
  let url_ = getBaseUrl() + '/api/curriculum';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function createCurriculumMutationKey(): MutationKey {
  return trimArrayEnd(['CurriculumClient', 'createCurriculum']);
}

export function useCreateCurriculumMutation<TContext>(
  options?: Omit<
    UseMutationOptions<number, unknown, Types.CreateCurriculumDto, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<number, unknown, Types.CreateCurriculumDto, TContext> {
  const key = createCurriculumMutationKey();

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (createCurriculumDto: Types.CreateCurriculumDto) =>
      Client.createCurriculum(createCurriculumDto),
    mutationKey: key,
  });
}

export function searchCurriculumsUrl(): string {
  let url_ = getBaseUrl() + '/api/curriculum';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

let searchCurriculumsDefaultOptions: Omit<
  UseQueryOptions<
    Types.CurriculumShortDto[],
    unknown,
    Types.CurriculumShortDto[]
  >,
  'queryKey' | 'queryFn'
> &
  Partial<
    Pick<
      UseQueryOptions<
        Types.CurriculumShortDto[],
        unknown,
        Types.CurriculumShortDto[]
      >,
      'queryFn'
    >
  > = {};
export function getSearchCurriculumsDefaultOptions() {
  return searchCurriculumsDefaultOptions;
}
export function setSearchCurriculumsDefaultOptions(
  options: typeof searchCurriculumsDefaultOptions,
) {
  searchCurriculumsDefaultOptions = options;
}

export function searchCurriculumsQueryKey(): QueryKey;
export function searchCurriculumsQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd(['CurriculumClient', 'searchCurriculums']);
}
export function __searchCurriculums(
  context: QueryFunctionContext,
  axiosConfig?: AxiosRequestConfig | undefined,
) {
  return Client.searchCurriculums(axiosConfig);
}

export function useSearchCurriculumsQuery<
  TSelectData = Types.CurriculumShortDto[],
  TError = unknown,
>(
  options?: Omit<
    UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData>,
    'queryKey'
  >,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;
export function useSearchCurriculumsQuery<
  TSelectData = Types.CurriculumShortDto[],
  TError = unknown,
>(...params: any[]): UseQueryResult<TSelectData, TError> {
  let options:
    | UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData>
    | undefined = undefined;
  let axiosConfig: AxiosRequestConfig | undefined = undefined;

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CurriculumShortDto[], TError, TSelectData>({
    queryFn: axiosConfig
      ? (context) => __searchCurriculums(context, axiosConfig)
      : __searchCurriculums,
    queryKey: searchCurriculumsQueryKey(),
    ...(searchCurriculumsDefaultOptions as unknown as Omit<
      UseQueryOptions<Types.CurriculumShortDto[], TError, TSelectData>,
      'queryKey'
    >),
    ...options,
  });
}

export function setSearchCurriculumsData(
  queryClient: QueryClient,
  updater: (
    data: Types.CurriculumShortDto[] | undefined,
  ) => Types.CurriculumShortDto[],
) {
  queryClient.setQueryData(searchCurriculumsQueryKey(), updater);
}

export function setSearchCurriculumsDataByQueryId(
  queryClient: QueryClient,
  queryKey: QueryKey,
  updater: (
    data: Types.CurriculumShortDto[] | undefined,
  ) => Types.CurriculumShortDto[],
) {
  queryClient.setQueryData(queryKey, updater);
}

export function updateCurriculumUrl(id: number): string {
  let url_ = getBaseUrl() + '/api/curriculum/{id}';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function updateCurriculumMutationKey(id: number): MutationKey {
  return trimArrayEnd(['CurriculumClient', 'updateCurriculum', id as any]);
}

export function useUpdateCurriculumMutation<TContext>(
  id: number,
  options?: Omit<
    UseMutationOptions<
      Types.CurriculumShortDto,
      unknown,
      Types.UpdateCurriculumDto,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<
  Types.CurriculumShortDto,
  unknown,
  Types.UpdateCurriculumDto,
  TContext
> {
  const key = updateCurriculumMutationKey(id);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (updateCurriculumDto: Types.UpdateCurriculumDto) =>
      Client.updateCurriculum(id, updateCurriculumDto),
    mutationKey: key,
  });
}

type UpdateCurriculum__MutationParameters =
  UpdateCurriculumCurriculumQueryParameters & {
    updateCurriculumDto: Types.UpdateCurriculumDto;
  };

export function useUpdateCurriculumMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      Types.CurriculumShortDto,
      unknown,
      UpdateCurriculum__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: UpdateCurriculumCurriculumQueryParameters },
): UseMutationResult<
  Types.CurriculumShortDto,
  unknown,
  UpdateCurriculum__MutationParameters,
  TContext
> {
  const key = updateCurriculumMutationKey(options?.parameters?.id!);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: UpdateCurriculum__MutationParameters) =>
      Client.updateCurriculum(
        data.id ?? options?.parameters?.id!,
        data.updateCurriculumDto,
      ),
    mutationKey: key,
  });
}

export function getCurriculumUrl(id: number): string {
  let url_ = getBaseUrl() + '/api/curriculum/{id}';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

let getCurriculumDefaultOptions: Omit<
  UseQueryOptions<Types.CurriculumDto, unknown, Types.CurriculumDto>,
  'queryKey' | 'queryFn'
> &
  Partial<
    Pick<
      UseQueryOptions<Types.CurriculumDto, unknown, Types.CurriculumDto>,
      'queryFn'
    >
  > = {};
export function getGetCurriculumDefaultOptions() {
  return getCurriculumDefaultOptions;
}
export function setGetCurriculumDefaultOptions(
  options: typeof getCurriculumDefaultOptions,
) {
  getCurriculumDefaultOptions = options;
}

export function getCurriculumQueryKey(id: number): QueryKey;
export function getCurriculumQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id } = params[0] as GetCurriculumCurriculumQueryParameters;

    return trimArrayEnd(['CurriculumClient', 'getCurriculum', id as any]);
  } else {
    return trimArrayEnd(['CurriculumClient', 'getCurriculum', ...params]);
  }
}
export function __getCurriculum(
  context: QueryFunctionContext,
  axiosConfig?: AxiosRequestConfig | undefined,
) {
  return Client.getCurriculum(context.queryKey[2] as number, axiosConfig);
}

export function useGetCurriculumQuery<
  TSelectData = Types.CurriculumDto,
  TError = unknown,
>(
  dto: GetCurriculumCurriculumQueryParameters,
  options?: Omit<
    UseQueryOptions<Types.CurriculumDto, TError, TSelectData>,
    'queryKey'
  >,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;

export function useGetCurriculumQuery<
  TSelectData = Types.CurriculumDto,
  TError = unknown,
>(
  id: number,
  options?: Omit<
    UseQueryOptions<Types.CurriculumDto, TError, TSelectData>,
    'queryKey'
  >,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;
export function useGetCurriculumQuery<
  TSelectData = Types.CurriculumDto,
  TError = unknown,
>(...params: any[]): UseQueryResult<TSelectData, TError> {
  let options:
    | UseQueryOptions<Types.CurriculumDto, TError, TSelectData>
    | undefined = undefined;
  let axiosConfig: AxiosRequestConfig | undefined = undefined;
  let id: any = undefined;

  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id } = params[0] as GetCurriculumCurriculumQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CurriculumDto, TError, TSelectData>({
    queryFn: axiosConfig
      ? (context) => __getCurriculum(context, axiosConfig)
      : __getCurriculum,
    queryKey: getCurriculumQueryKey(id),
    ...(getCurriculumDefaultOptions as unknown as Omit<
      UseQueryOptions<Types.CurriculumDto, TError, TSelectData>,
      'queryKey'
    >),
    ...options,
  });
}

export function setGetCurriculumData(
  queryClient: QueryClient,
  updater: (data: Types.CurriculumDto | undefined) => Types.CurriculumDto,
  id: number,
) {
  queryClient.setQueryData(getCurriculumQueryKey(id), updater);
}

export function setGetCurriculumDataByQueryId(
  queryClient: QueryClient,
  queryKey: QueryKey,
  updater: (data: Types.CurriculumDto | undefined) => Types.CurriculumDto,
) {
  queryClient.setQueryData(queryKey, updater);
}

export function deleteCurriculumUrl(id: number): string {
  let url_ = getBaseUrl() + '/api/curriculum/{id}';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function deleteCurriculumMutationKey(id: number): MutationKey {
  return trimArrayEnd(['CurriculumClient', 'deleteCurriculum', id as any]);
}

export function useDeleteCurriculumMutation<TContext>(
  id: number,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteCurriculumMutationKey(id);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.deleteCurriculum(id),
    mutationKey: key,
  });
}

type DeleteCurriculum__MutationParameters =
  DeleteCurriculumCurriculumQueryParameters;

export function useDeleteCurriculumMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      DeleteCurriculum__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: DeleteCurriculumCurriculumQueryParameters },
): UseMutationResult<
  void,
  unknown,
  DeleteCurriculum__MutationParameters,
  TContext
> {
  const key = deleteCurriculumMutationKey(options?.parameters?.id!);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: DeleteCurriculum__MutationParameters) =>
      Client.deleteCurriculum(data.id ?? options?.parameters?.id!),
    mutationKey: key,
  });
}

export function setCurriculumSettingsUrl(id: number): string {
  let url_ = getBaseUrl() + '/api/curriculum/{id}/settings';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function setCurriculumSettingsMutationKey(id: number): MutationKey {
  return trimArrayEnd(['CurriculumClient', 'setCurriculumSettings', id as any]);
}

export function useSetCurriculumSettingsMutation<TContext>(
  id: number,
  options?: Omit<
    UseMutationOptions<void, unknown, Types.SetCurriculumSettingsDto, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, Types.SetCurriculumSettingsDto, TContext> {
  const key = setCurriculumSettingsMutationKey(id);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (setCurriculumSettingsDto: Types.SetCurriculumSettingsDto) =>
      Client.setCurriculumSettings(id, setCurriculumSettingsDto),
    mutationKey: key,
  });
}

type SetCurriculumSettings__MutationParameters =
  SetCurriculumSettingsCurriculumQueryParameters & {
    setCurriculumSettingsDto: Types.SetCurriculumSettingsDto;
  };

export function useSetCurriculumSettingsMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      SetCurriculumSettings__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: SetCurriculumSettingsCurriculumQueryParameters },
): UseMutationResult<
  void,
  unknown,
  SetCurriculumSettings__MutationParameters,
  TContext
> {
  const key = setCurriculumSettingsMutationKey(options?.parameters?.id!);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: SetCurriculumSettings__MutationParameters) =>
      Client.setCurriculumSettings(
        data.id ?? options?.parameters?.id!,
        data.setCurriculumSettingsDto,
      ),
    mutationKey: key,
  });
}

export function getUserPermissionsForCurriculumByIdUrl(id: number): string {
  let url_ =
    getBaseUrl() + '/api/curriculum/user-permissions-for-curriculum/{id}';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

let getUserPermissionsForCurriculumByIdDefaultOptions: Omit<
  UseQueryOptions<string[], unknown, string[]>,
  'queryKey' | 'queryFn'
> &
  Partial<Pick<UseQueryOptions<string[], unknown, string[]>, 'queryFn'>> = {};
export function getGetUserPermissionsForCurriculumByIdDefaultOptions() {
  return getUserPermissionsForCurriculumByIdDefaultOptions;
}
export function setGetUserPermissionsForCurriculumByIdDefaultOptions(
  options: typeof getUserPermissionsForCurriculumByIdDefaultOptions,
) {
  getUserPermissionsForCurriculumByIdDefaultOptions = options;
}

export function getUserPermissionsForCurriculumByIdQueryKey(
  id: number,
): QueryKey;
export function getUserPermissionsForCurriculumByIdQueryKey(
  ...params: any[]
): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id } =
      params[0] as GetUserPermissionsForCurriculumByIdCurriculumQueryParameters;

    return trimArrayEnd([
      'CurriculumClient',
      'getUserPermissionsForCurriculumById',
      id as any,
    ]);
  } else {
    return trimArrayEnd([
      'CurriculumClient',
      'getUserPermissionsForCurriculumById',
      ...params,
    ]);
  }
}
export function __getUserPermissionsForCurriculumById(
  context: QueryFunctionContext,
  axiosConfig?: AxiosRequestConfig | undefined,
) {
  return Client.getUserPermissionsForCurriculumById(
    context.queryKey[2] as number,
    axiosConfig,
  );
}

export function useGetUserPermissionsForCurriculumByIdQuery<
  TSelectData = string[],
  TError = unknown,
>(
  dto: GetUserPermissionsForCurriculumByIdCurriculumQueryParameters,
  options?: Omit<UseQueryOptions<string[], TError, TSelectData>, 'queryKey'>,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;

export function useGetUserPermissionsForCurriculumByIdQuery<
  TSelectData = string[],
  TError = unknown,
>(
  id: number,
  options?: Omit<UseQueryOptions<string[], TError, TSelectData>, 'queryKey'>,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;
export function useGetUserPermissionsForCurriculumByIdQuery<
  TSelectData = string[],
  TError = unknown,
>(...params: any[]): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<string[], TError, TSelectData> | undefined =
    undefined;
  let axiosConfig: AxiosRequestConfig | undefined = undefined;
  let id: any = undefined;

  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id } =
        params[0] as GetUserPermissionsForCurriculumByIdCurriculumQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<string[], TError, TSelectData>({
    queryFn: axiosConfig
      ? (context) => __getUserPermissionsForCurriculumById(context, axiosConfig)
      : __getUserPermissionsForCurriculumById,
    queryKey: getUserPermissionsForCurriculumByIdQueryKey(id),
    ...(getUserPermissionsForCurriculumByIdDefaultOptions as unknown as Omit<
      UseQueryOptions<string[], TError, TSelectData>,
      'queryKey'
    >),
    ...options,
  });
}

export function setGetUserPermissionsForCurriculumByIdData(
  queryClient: QueryClient,
  updater: (data: string[] | undefined) => string[],
  id: number,
) {
  queryClient.setQueryData(
    getUserPermissionsForCurriculumByIdQueryKey(id),
    updater,
  );
}

export function setGetUserPermissionsForCurriculumByIdDataByQueryId(
  queryClient: QueryClient,
  queryKey: QueryKey,
  updater: (data: string[] | undefined) => string[],
) {
  queryClient.setQueryData(queryKey, updater);
}

export function connectCurriculumWithDivisionUrl(
  id: number,
  curriculumId?: number | undefined,
): string {
  let url_ =
    getBaseUrl() + '/api/curriculum/connect-curriculum-with-division/{id}?';
  if (id === undefined || id === null)
    throw new Error("The parameter 'id' must be defined.");
  url_ = url_.replace('{id}', encodeURIComponent('' + id));
  if (curriculumId === null)
    throw new Error("The parameter 'curriculumId' cannot be null.");
  else if (curriculumId !== undefined)
    url_ += 'curriculumId=' + encodeURIComponent('' + curriculumId) + '&';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function connectCurriculumWithDivisionMutationKey(
  id: number,
  curriculumId?: number | undefined,
): MutationKey {
  return trimArrayEnd([
    'CurriculumClient',
    'connectCurriculumWithDivision',
    id as any,
    curriculumId as any,
  ]);
}

export function useConnectCurriculumWithDivisionMutation<TContext>(
  id: number,
  curriculumId?: number | undefined,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = connectCurriculumWithDivisionMutationKey(id, curriculumId);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.connectCurriculumWithDivision(id, curriculumId),
    mutationKey: key,
  });
}

type ConnectCurriculumWithDivision__MutationParameters =
  ConnectCurriculumWithDivisionCurriculumQueryParameters;

export function useConnectCurriculumWithDivisionMutationWithParameters<
  TContext,
>(
  options?: Omit<
    UseMutationOptions<
      void,
      unknown,
      ConnectCurriculumWithDivision__MutationParameters,
      TContext
    >,
    'mutationKey' | 'mutationFn'
  > & { parameters?: ConnectCurriculumWithDivisionCurriculumQueryParameters },
): UseMutationResult<
  void,
  unknown,
  ConnectCurriculumWithDivision__MutationParameters,
  TContext
> {
  const key = connectCurriculumWithDivisionMutationKey(
    options?.parameters?.id!,
    options?.parameters?.curriculumId!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: ConnectCurriculumWithDivision__MutationParameters) =>
      Client.connectCurriculumWithDivision(
        data.id ?? options?.parameters?.id!,
        data.curriculumId ?? options?.parameters?.curriculumId!,
      ),
    mutationKey: key,
  });
}
