//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './DocumentGenerationClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GeneratePdfDocumentGenerationQueryParameters = {
  curriculumId: number ;
}

export function generatePdfUrl(curriculumId: number): string {
  let url_ = getBaseUrl() + "/curriculum/{curriculumId}/document";
if (curriculumId === undefined || curriculumId === null)
  throw new Error("The parameter 'curriculumId' must be defined.");
url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function generatePdfMutationKey(curriculumId: number): MutationKey {
  return trimArrayEnd([
      'DocumentGenerationClient',
      'generatePdf',
      curriculumId as any,
    ]);
}

export function useGeneratePdfMutation<TContext>(curriculumId: number, options?: Omit<UseMutationOptions<Types.FileResponse, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.FileResponse, unknown, void, TContext> {
  const key = generatePdfMutationKey(curriculumId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.generatePdf(curriculumId),
    mutationKey: key,
  });
}
  
type GeneratePdf__MutationParameters = GeneratePdfDocumentGenerationQueryParameters

export function useGeneratePdfMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.FileResponse, unknown, GeneratePdf__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: GeneratePdfDocumentGenerationQueryParameters}): UseMutationResult<Types.FileResponse, unknown, GeneratePdf__MutationParameters, TContext> {
  const key = generatePdfMutationKey(options?.parameters?.curriculumId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: GeneratePdf__MutationParameters) => Client.generatePdf(data.curriculumId ?? options?.parameters?.curriculumId!),
  mutationKey: key,
});
}