//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function fgaAdd(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  config?: AxiosRequestConfig | undefined,
): Promise<void> {
  let url_ = getBaseUrl() + '/api/fga/test-add?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');

  let options_: AxiosRequestConfig = {
    ..._requestConfigFgaAdd,
    ...config,
    method: 'POST',
    url: url_,
    headers: {
      ..._requestConfigFgaAdd?.headers,
    },
  };

  return getAxios()
    .request(options_)
    .catch((_error: any) => {
      if (isAxiosError(_error) && _error.response) {
        return _error.response;
      } else {
        throw _error;
      }
    })
    .then((_response: AxiosResponse) => {
      return processFgaAdd(_response);
    });
}

function processFgaAdd(response: AxiosResponse): Promise<void> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && typeof response.headers === 'object') {
    for (let k in response.headers) {
      if (response.headers.hasOwnProperty(k)) {
        _headers[k] = response.headers[k];
      }
    }
  }
  if (status === 200) {
    const _responseText = response.data;
    return Promise.resolve<void>(null as any);
  } else if (status !== 200 && status !== 204) {
    const _responseText = response.data;
    return throwException(
      'An unexpected server error occurred.',
      status,
      _responseText,
      _headers,
    );
  }
  return Promise.resolve<void>(null as any);
}

export function fgaCheck(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  config?: AxiosRequestConfig | undefined,
): Promise<void> {
  let url_ = getBaseUrl() + '/api/fga/test-check?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');

  let options_: AxiosRequestConfig = {
    ..._requestConfigFgaCheck,
    ...config,
    method: 'GET',
    url: url_,
    headers: {
      ..._requestConfigFgaCheck?.headers,
    },
  };

  return getAxios()
    .request(options_)
    .catch((_error: any) => {
      if (isAxiosError(_error) && _error.response) {
        return _error.response;
      } else {
        throw _error;
      }
    })
    .then((_response: AxiosResponse) => {
      return processFgaCheck(_response);
    });
}

function processFgaCheck(response: AxiosResponse): Promise<void> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && typeof response.headers === 'object') {
    for (let k in response.headers) {
      if (response.headers.hasOwnProperty(k)) {
        _headers[k] = response.headers[k];
      }
    }
  }
  if (status === 200) {
    const _responseText = response.data;
    return Promise.resolve<void>(null as any);
  } else if (status !== 200 && status !== 204) {
    const _responseText = response.data;
    return throwException(
      'An unexpected server error occurred.',
      status,
      _responseText,
      _headers,
    );
  }
  return Promise.resolve<void>(null as any);
}

export function fgaDelete(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  config?: AxiosRequestConfig | undefined,
): Promise<void> {
  let url_ = getBaseUrl() + '/api/fga/test-delete?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');

  let options_: AxiosRequestConfig = {
    ..._requestConfigFgaDelete,
    ...config,
    method: 'DELETE',
    url: url_,
    headers: {
      ..._requestConfigFgaDelete?.headers,
    },
  };

  return getAxios()
    .request(options_)
    .catch((_error: any) => {
      if (isAxiosError(_error) && _error.response) {
        return _error.response;
      } else {
        throw _error;
      }
    })
    .then((_response: AxiosResponse) => {
      return processFgaDelete(_response);
    });
}

function processFgaDelete(response: AxiosResponse): Promise<void> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && typeof response.headers === 'object') {
    for (let k in response.headers) {
      if (response.headers.hasOwnProperty(k)) {
        _headers[k] = response.headers[k];
      }
    }
  }
  if (status === 200) {
    const _responseText = response.data;
    return Promise.resolve<void>(null as any);
  } else if (status !== 200 && status !== 204) {
    const _responseText = response.data;
    return throwException(
      'An unexpected server error occurred.',
      status,
      _responseText,
      _headers,
    );
  }
  return Promise.resolve<void>(null as any);
}

export function getFgaStore(
  config?: AxiosRequestConfig | undefined,
): Promise<Types.ReadResponse> {
  let url_ = getBaseUrl() + '/api/fga/get-fga-model';
  url_ = url_.replace(/[?&]$/, '');

  let options_: AxiosRequestConfig = {
    ..._requestConfigGetFgaStore,
    ...config,
    method: 'GET',
    url: url_,
    headers: {
      ..._requestConfigGetFgaStore?.headers,
      Accept: 'application/json',
    },
  };

  return getAxios()
    .request(options_)
    .catch((_error: any) => {
      if (isAxiosError(_error) && _error.response) {
        return _error.response;
      } else {
        throw _error;
      }
    })
    .then((_response: AxiosResponse) => {
      return processGetFgaStore(_response);
    });
}

function processGetFgaStore(
  response: AxiosResponse,
): Promise<Types.ReadResponse> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && typeof response.headers === 'object') {
    for (let k in response.headers) {
      if (response.headers.hasOwnProperty(k)) {
        _headers[k] = response.headers[k];
      }
    }
  }
  if (status === 200) {
    const _responseText = response.data;
    let result200: any = null;
    let resultData200 = _responseText;
    result200 = Types.initReadResponse(resultData200);
    return Promise.resolve<Types.ReadResponse>(result200);
  } else if (status !== 200 && status !== 204) {
    const _responseText = response.data;
    return throwException(
      'An unexpected server error occurred.',
      status,
      _responseText,
      _headers,
    );
  }
  return Promise.resolve<Types.ReadResponse>(null as any);
}

export function makeAllUsersAdmin(
  config?: AxiosRequestConfig | undefined,
): Promise<void> {
  let url_ = getBaseUrl() + '/api/fga/make-all-users-admin';
  url_ = url_.replace(/[?&]$/, '');

  let options_: AxiosRequestConfig = {
    ..._requestConfigMakeAllUsersAdmin,
    ...config,
    method: 'POST',
    url: url_,
    headers: {
      ..._requestConfigMakeAllUsersAdmin?.headers,
    },
  };

  return getAxios()
    .request(options_)
    .catch((_error: any) => {
      if (isAxiosError(_error) && _error.response) {
        return _error.response;
      } else {
        throw _error;
      }
    })
    .then((_response: AxiosResponse) => {
      return processMakeAllUsersAdmin(_response);
    });
}

function processMakeAllUsersAdmin(response: AxiosResponse): Promise<void> {
  const status = response.status;
  let _headers: any = {};
  if (response.headers && typeof response.headers === 'object') {
    for (let k in response.headers) {
      if (response.headers.hasOwnProperty(k)) {
        _headers[k] = response.headers[k];
      }
    }
  }
  if (status === 200) {
    const _responseText = response.data;
    return Promise.resolve<void>(null as any);
  } else if (status !== 200 && status !== 204) {
    const _responseText = response.data;
    return throwException(
      'An unexpected server error occurred.',
      status,
      _responseText,
      _headers,
    );
  }
  return Promise.resolve<void>(null as any);
}
let _requestConfigFgaAdd: Partial<AxiosRequestConfig> | null;
export function getFgaAddRequestConfig() {
  return _requestConfigFgaAdd;
}
export function setFgaAddRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigFgaAdd = value;
}
export function patchFgaAddRequestConfig(
  patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>,
) {
  _requestConfigFgaAdd = patch(_requestConfigFgaAdd ?? {});
}

let _requestConfigFgaCheck: Partial<AxiosRequestConfig> | null;
export function getFgaCheckRequestConfig() {
  return _requestConfigFgaCheck;
}
export function setFgaCheckRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigFgaCheck = value;
}
export function patchFgaCheckRequestConfig(
  patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>,
) {
  _requestConfigFgaCheck = patch(_requestConfigFgaCheck ?? {});
}

let _requestConfigFgaDelete: Partial<AxiosRequestConfig> | null;
export function getFgaDeleteRequestConfig() {
  return _requestConfigFgaDelete;
}
export function setFgaDeleteRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigFgaDelete = value;
}
export function patchFgaDeleteRequestConfig(
  patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>,
) {
  _requestConfigFgaDelete = patch(_requestConfigFgaDelete ?? {});
}

let _requestConfigGetFgaStore: Partial<AxiosRequestConfig> | null;
export function getGetFgaStoreRequestConfig() {
  return _requestConfigGetFgaStore;
}
export function setGetFgaStoreRequestConfig(
  value: Partial<AxiosRequestConfig>,
) {
  _requestConfigGetFgaStore = value;
}
export function patchGetFgaStoreRequestConfig(
  patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>,
) {
  _requestConfigGetFgaStore = patch(_requestConfigGetFgaStore ?? {});
}

let _requestConfigMakeAllUsersAdmin: Partial<AxiosRequestConfig> | null;
export function getMakeAllUsersAdminRequestConfig() {
  return _requestConfigMakeAllUsersAdmin;
}
export function setMakeAllUsersAdminRequestConfig(
  value: Partial<AxiosRequestConfig>,
) {
  _requestConfigMakeAllUsersAdmin = value;
}
export function patchMakeAllUsersAdminRequestConfig(
  patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>,
) {
  _requestConfigMakeAllUsersAdmin = patch(
    _requestConfigMakeAllUsersAdmin ?? {},
  );
}
