//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type {
  UseQueryResult,
  QueryFunctionContext,
  UseQueryOptions,
  QueryClient,
  QueryKey,
  MutationKey,
  UseMutationOptions,
  UseMutationResult,
  QueryMeta,
  MutationMeta,
} from '@tanstack/react-query';
import {
  trimArrayEnd,
  isParameterObject,
  getBaseUrl,
  addMetaToOptions,
} from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './FGAClient';
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type FgaAddFGAQueryParameters = {
  user?: string | undefined;
  relation?: string | undefined;
  obj?: string | undefined;
};

export type FgaCheckFGAQueryParameters = {
  user?: string | undefined;
  relation?: string | undefined;
  obj?: string | undefined;
};

export type FgaDeleteFGAQueryParameters = {
  user?: string | undefined;
  relation?: string | undefined;
  obj?: string | undefined;
};

export function fgaAddUrl(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): string {
  let url_ = getBaseUrl() + '/api/fga/test-add?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function fgaAddMutationKey(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): MutationKey {
  return trimArrayEnd([
    'FGAClient',
    'fgaAdd',
    user as any,
    relation as any,
    obj as any,
  ]);
}

export function useFgaAddMutation<TContext>(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = fgaAddMutationKey(user, relation, obj);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.fgaAdd(user, relation, obj),
    mutationKey: key,
  });
}

type FgaAdd__MutationParameters = FgaAddFGAQueryParameters;

export function useFgaAddMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<void, unknown, FgaAdd__MutationParameters, TContext>,
    'mutationKey' | 'mutationFn'
  > & { parameters?: FgaAddFGAQueryParameters },
): UseMutationResult<void, unknown, FgaAdd__MutationParameters, TContext> {
  const key = fgaAddMutationKey(
    options?.parameters?.user!,
    options?.parameters?.relation!,
    options?.parameters?.obj!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: FgaAdd__MutationParameters) =>
      Client.fgaAdd(
        data.user ?? options?.parameters?.user!,
        data.relation ?? options?.parameters?.relation!,
        data.obj ?? options?.parameters?.obj!,
      ),
    mutationKey: key,
  });
}

export function fgaCheckUrl(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): string {
  let url_ = getBaseUrl() + '/api/fga/test-check?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

let fgaCheckDefaultOptions: Omit<
  UseQueryOptions<void, unknown, void>,
  'queryKey' | 'queryFn'
> &
  Partial<Pick<UseQueryOptions<void, unknown, void>, 'queryFn'>> = {};
export function getFgaCheckDefaultOptions() {
  return fgaCheckDefaultOptions;
}
export function setFgaCheckDefaultOptions(
  options: typeof fgaCheckDefaultOptions,
) {
  fgaCheckDefaultOptions = options;
}

export function fgaCheckQueryKey(dto: FgaCheckFGAQueryParameters): QueryKey;
export function fgaCheckQueryKey(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): QueryKey;
export function fgaCheckQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { user, relation, obj } = params[0] as FgaCheckFGAQueryParameters;

    return trimArrayEnd([
      'FGAClient',
      'fgaCheck',
      user as any,
      relation as any,
      obj as any,
    ]);
  } else {
    return trimArrayEnd(['FGAClient', 'fgaCheck', ...params]);
  }
}
export function __fgaCheck(
  context: QueryFunctionContext,
  axiosConfig?: AxiosRequestConfig | undefined,
) {
  return Client.fgaCheck(
    context.queryKey[2] as string | undefined,
    context.queryKey[3] as string | undefined,
    context.queryKey[4] as string | undefined,
    axiosConfig,
  );
}

export function useFgaCheckQuery<TSelectData = void, TError = unknown>(
  dto: FgaCheckFGAQueryParameters,
  options?: Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;

export function useFgaCheckQuery<TSelectData = void, TError = unknown>(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  options?: Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;
export function useFgaCheckQuery<TSelectData = void, TError = unknown>(
  ...params: any[]
): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<void, TError, TSelectData> | undefined =
    undefined;
  let axiosConfig: AxiosRequestConfig | undefined = undefined;
  let user: any = undefined;
  let relation: any = undefined;
  let obj: any = undefined;

  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ user, relation, obj } = params[0] as FgaCheckFGAQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [user, relation, obj, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<void, TError, TSelectData>({
    queryFn: axiosConfig
      ? (context) => __fgaCheck(context, axiosConfig)
      : __fgaCheck,
    queryKey: fgaCheckQueryKey(user, relation, obj),
    ...(fgaCheckDefaultOptions as unknown as Omit<
      UseQueryOptions<void, TError, TSelectData>,
      'queryKey'
    >),
    ...options,
  });
}

export function setFgaCheckData(
  queryClient: QueryClient,
  updater: (data: void | undefined) => void,
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
) {
  queryClient.setQueryData(fgaCheckQueryKey(user, relation, obj), updater);
}

export function setFgaCheckDataByQueryId(
  queryClient: QueryClient,
  queryKey: QueryKey,
  updater: (data: void | undefined) => void,
) {
  queryClient.setQueryData(queryKey, updater);
}

export function fgaDeleteUrl(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): string {
  let url_ = getBaseUrl() + '/api/fga/test-delete?';
  if (user === null) throw new Error("The parameter 'user' cannot be null.");
  else if (user !== undefined)
    url_ += 'user=' + encodeURIComponent('' + user) + '&';
  if (relation === null)
    throw new Error("The parameter 'relation' cannot be null.");
  else if (relation !== undefined)
    url_ += 'relation=' + encodeURIComponent('' + relation) + '&';
  if (obj === null) throw new Error("The parameter 'obj' cannot be null.");
  else if (obj !== undefined)
    url_ += 'obj=' + encodeURIComponent('' + obj) + '&';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function fgaDeleteMutationKey(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
): MutationKey {
  return trimArrayEnd([
    'FGAClient',
    'fgaDelete',
    user as any,
    relation as any,
    obj as any,
  ]);
}

export function useFgaDeleteMutation<TContext>(
  user?: string | undefined,
  relation?: string | undefined,
  obj?: string | undefined,
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = fgaDeleteMutationKey(user, relation, obj);

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.fgaDelete(user, relation, obj),
    mutationKey: key,
  });
}

type FgaDelete__MutationParameters = FgaDeleteFGAQueryParameters;

export function useFgaDeleteMutationWithParameters<TContext>(
  options?: Omit<
    UseMutationOptions<void, unknown, FgaDelete__MutationParameters, TContext>,
    'mutationKey' | 'mutationFn'
  > & { parameters?: FgaDeleteFGAQueryParameters },
): UseMutationResult<void, unknown, FgaDelete__MutationParameters, TContext> {
  const key = fgaDeleteMutationKey(
    options?.parameters?.user!,
    options?.parameters?.relation!,
    options?.parameters?.obj!,
  );

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: (data: FgaDelete__MutationParameters) =>
      Client.fgaDelete(
        data.user ?? options?.parameters?.user!,
        data.relation ?? options?.parameters?.relation!,
        data.obj ?? options?.parameters?.obj!,
      ),
    mutationKey: key,
  });
}

export function getFgaStoreUrl(): string {
  let url_ = getBaseUrl() + '/api/fga/get-fga-model';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

let getFgaStoreDefaultOptions: Omit<
  UseQueryOptions<Types.ReadResponse, unknown, Types.ReadResponse>,
  'queryKey' | 'queryFn'
> &
  Partial<
    Pick<
      UseQueryOptions<Types.ReadResponse, unknown, Types.ReadResponse>,
      'queryFn'
    >
  > = {};
export function getGetFgaStoreDefaultOptions() {
  return getFgaStoreDefaultOptions;
}
export function setGetFgaStoreDefaultOptions(
  options: typeof getFgaStoreDefaultOptions,
) {
  getFgaStoreDefaultOptions = options;
}

export function getFgaStoreQueryKey(): QueryKey;
export function getFgaStoreQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd(['FGAClient', 'getFgaStore']);
}
export function __getFgaStore(
  context: QueryFunctionContext,
  axiosConfig?: AxiosRequestConfig | undefined,
) {
  return Client.getFgaStore(axiosConfig);
}

export function useGetFgaStoreQuery<
  TSelectData = Types.ReadResponse,
  TError = unknown,
>(
  options?: Omit<
    UseQueryOptions<Types.ReadResponse, TError, TSelectData>,
    'queryKey'
  >,
  axiosConfig?: Partial<AxiosRequestConfig>,
): UseQueryResult<TSelectData, TError>;
export function useGetFgaStoreQuery<
  TSelectData = Types.ReadResponse,
  TError = unknown,
>(...params: any[]): UseQueryResult<TSelectData, TError> {
  let options:
    | UseQueryOptions<Types.ReadResponse, TError, TSelectData>
    | undefined = undefined;
  let axiosConfig: AxiosRequestConfig | undefined = undefined;

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.ReadResponse, TError, TSelectData>({
    queryFn: axiosConfig
      ? (context) => __getFgaStore(context, axiosConfig)
      : __getFgaStore,
    queryKey: getFgaStoreQueryKey(),
    ...(getFgaStoreDefaultOptions as unknown as Omit<
      UseQueryOptions<Types.ReadResponse, TError, TSelectData>,
      'queryKey'
    >),
    ...options,
  });
}

export function setGetFgaStoreData(
  queryClient: QueryClient,
  updater: (data: Types.ReadResponse | undefined) => Types.ReadResponse,
) {
  queryClient.setQueryData(getFgaStoreQueryKey(), updater);
}

export function setGetFgaStoreDataByQueryId(
  queryClient: QueryClient,
  queryKey: QueryKey,
  updater: (data: Types.ReadResponse | undefined) => Types.ReadResponse,
) {
  queryClient.setQueryData(queryKey, updater);
}

export function makeAllUsersAdminUrl(): string {
  let url_ = getBaseUrl() + '/api/fga/make-all-users-admin';
  url_ = url_.replace(/[?&]$/, '');
  return url_;
}

export function makeAllUsersAdminMutationKey(): MutationKey {
  return trimArrayEnd(['FGAClient', 'makeAllUsersAdmin']);
}

export function useMakeAllUsersAdminMutation<TContext>(
  options?: Omit<
    UseMutationOptions<void, unknown, void, TContext>,
    'mutationKey' | 'mutationFn'
  >,
): UseMutationResult<void, unknown, void, TContext> {
  const key = makeAllUsersAdminMutationKey();

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useMutation({
    ...options,
    mutationFn: () => Client.makeAllUsersAdmin(),
    mutationKey: key,
  });
}
