//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function createUpdate(curriculumId: number, academicActivityId: number, createHoursDistribution: Types.CreateUpdateHoursDistributionDto, semesterId?: number | undefined, atomId?: number | undefined, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/curriculum/{curriculumId}/academic-activity/{academicActivityId}/hours-distribution?";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
    if (academicActivityId === undefined || academicActivityId === null)
      throw new Error("The parameter 'academicActivityId' must be defined.");
    url_ = url_.replace("{academicActivityId}", encodeURIComponent("" + academicActivityId));
    if (semesterId === null)
        throw new Error("The parameter 'semesterId' cannot be null.");
    else if (semesterId !== undefined)
        url_ += "semesterId=" + encodeURIComponent("" + semesterId) + "&";
    if (atomId === null)
        throw new Error("The parameter 'atomId' cannot be null.");
    else if (atomId !== undefined)
        url_ += "atomId=" + encodeURIComponent("" + atomId) + "&";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateUpdateHoursDistributionDto(createHoursDistribution);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreateUpdate,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreateUpdate?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreateUpdate(_response);
    });
}

function processCreateUpdate(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function delete_(curriculumId: number, academicActivityId: number, semesterId?: number | undefined, atomId?: number | undefined, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/curriculum/{curriculumId}/academic-activity/{academicActivityId}/hours-distribution?";
    if (curriculumId === undefined || curriculumId === null)
      throw new Error("The parameter 'curriculumId' must be defined.");
    url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
    if (academicActivityId === undefined || academicActivityId === null)
      throw new Error("The parameter 'academicActivityId' must be defined.");
    url_ = url_.replace("{academicActivityId}", encodeURIComponent("" + academicActivityId));
    if (semesterId === null)
        throw new Error("The parameter 'semesterId' cannot be null.");
    else if (semesterId !== undefined)
        url_ += "semesterId=" + encodeURIComponent("" + semesterId) + "&";
    if (atomId === null)
        throw new Error("The parameter 'atomId' cannot be null.");
    else if (atomId !== undefined)
        url_ += "atomId=" + encodeURIComponent("" + atomId) + "&";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDelete,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDelete?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDelete(_response);
    });
}

function processDelete(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigCreateUpdate: Partial<AxiosRequestConfig> | null;
export function getCreateUpdateRequestConfig() {
  return _requestConfigCreateUpdate;
}
export function setCreateUpdateRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreateUpdate = value;
}
export function patchCreateUpdateRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreateUpdate = patch(_requestConfigCreateUpdate ?? {});
}

let _requestConfigDelete: Partial<AxiosRequestConfig> | null;
export function getDeleteRequestConfig() {
  return _requestConfigDelete;
}
export function setDeleteRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDelete = value;
}
export function patchDeleteRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDelete = patch(_requestConfigDelete ?? {});
}