//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './ModuleClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type UpdateModuleModuleQueryParameters = {
  id: number ;
}

export type DeleteModuleModuleQueryParameters = {
  id: number ;
}

export function createModuleUrl(): string {
  let url_ = getBaseUrl() + "/module";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createModuleMutationKey(): MutationKey {
  return trimArrayEnd([
      'ModuleClient',
      'createModule',
    ]);
}

export function useCreateModuleMutation<TContext>(options?: Omit<UseMutationOptions<number, unknown, Types.CreateModuleDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<number, unknown, Types.CreateModuleDto, TContext> {
  const key = createModuleMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (createModuleDto: Types.CreateModuleDto) => Client.createModule(createModuleDto),
    mutationKey: key,
  });
}
  
export function updateModuleUrl(id: number): string {
  let url_ = getBaseUrl() + "/module/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateModuleMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'ModuleClient',
      'updateModule',
      id as any,
    ]);
}

export function useUpdateModuleMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, Types.UpdateModuleDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.UpdateModuleDto, TContext> {
  const key = updateModuleMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (updateModuleDto: Types.UpdateModuleDto) => Client.updateModule(id, updateModuleDto),
    mutationKey: key,
  });
}
  
type UpdateModule__MutationParameters = UpdateModuleModuleQueryParameters & {
  updateModuleDto: Types.UpdateModuleDto;
}

export function useUpdateModuleMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, UpdateModule__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: UpdateModuleModuleQueryParameters}): UseMutationResult<void, unknown, UpdateModule__MutationParameters, TContext> {
  const key = updateModuleMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: UpdateModule__MutationParameters) => Client.updateModule(data.id ?? options?.parameters?.id!, data.updateModuleDto),
  mutationKey: key,
});
}
  
export function deleteModuleUrl(id: number): string {
  let url_ = getBaseUrl() + "/module/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteModuleMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'ModuleClient',
      'deleteModule',
      id as any,
    ]);
}

export function useDeleteModuleMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteModuleMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteModule(id),
    mutationKey: key,
  });
}
  
type DeleteModule__MutationParameters = DeleteModuleModuleQueryParameters

export function useDeleteModuleMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteModule__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteModuleModuleQueryParameters}): UseMutationResult<void, unknown, DeleteModule__MutationParameters, TContext> {
  const key = deleteModuleMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteModule__MutationParameters) => Client.deleteModule(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}