//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './SemestersClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetSemestersSemestersQueryParameters = {
  curriculumId: number ;
}

export function getSemestersUrl(curriculumId: number): string {
  let url_ = getBaseUrl() + "/api/semester/{curriculumId}";
if (curriculumId === undefined || curriculumId === null)
  throw new Error("The parameter 'curriculumId' must be defined.");
url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getSemestersDefaultOptions: Omit<UseQueryOptions<Types.RefModuleSemesterDto[], unknown, Types.RefModuleSemesterDto[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.RefModuleSemesterDto[], unknown, Types.RefModuleSemesterDto[]>, 'queryFn'>> = {
};
export function getGetSemestersDefaultOptions() {
  return getSemestersDefaultOptions;
};
export function setGetSemestersDefaultOptions(options: typeof getSemestersDefaultOptions) {
  getSemestersDefaultOptions = options;
}

export function getSemestersQueryKey(curriculumId: number): QueryKey;
export function getSemestersQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { curriculumId,  } = params[0] as GetSemestersSemestersQueryParameters;

    return trimArrayEnd([
        'SemestersClient',
        'getSemesters',
        curriculumId as any,
      ]);
  } else {
    return trimArrayEnd([
        'SemestersClient',
        'getSemesters',
        ...params
      ]);
  }
}
export function __getSemesters(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getSemesters(
      context.queryKey[2] as number,axiosConfig    );
}

export function useGetSemestersQuery<TSelectData = Types.RefModuleSemesterDto[], TError = unknown>(dto: GetSemestersSemestersQueryParameters, options?: Omit<UseQueryOptions<Types.RefModuleSemesterDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetSemestersQuery<TSelectData = Types.RefModuleSemesterDto[], TError = unknown>(curriculumId: number, options?: Omit<UseQueryOptions<Types.RefModuleSemesterDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetSemestersQuery<TSelectData = Types.RefModuleSemesterDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.RefModuleSemesterDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let curriculumId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ curriculumId,  } = params[0] as GetSemestersSemestersQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [curriculumId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.RefModuleSemesterDto[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getSemesters(context, axiosConfig) : __getSemesters,
    queryKey: getSemestersQueryKey(curriculumId),
    ...getSemestersDefaultOptions as unknown as Omit<UseQueryOptions<Types.RefModuleSemesterDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetSemestersData(queryClient: QueryClient, updater: (data: Types.RefModuleSemesterDto[] | undefined) => Types.RefModuleSemesterDto[], curriculumId: number) {
  queryClient.setQueryData(getSemestersQueryKey(curriculumId),
    updater
  );
}

export function setGetSemestersDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.RefModuleSemesterDto[] | undefined) => Types.RefModuleSemesterDto[]) {
  queryClient.setQueryData(queryKey, updater);
}