//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './ValidationClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetValidationErrorsValidationQueryParameters = {
  curriculumId: number ;
}

export function getValidationErrorsUrl(curriculumId: number): string {
  let url_ = getBaseUrl() + "/validation/{curriculumId}";
if (curriculumId === undefined || curriculumId === null)
  throw new Error("The parameter 'curriculumId' must be defined.");
url_ = url_.replace("{curriculumId}", encodeURIComponent("" + curriculumId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getValidationErrorsDefaultOptions: Omit<UseQueryOptions<Types.ValidationError[], unknown, Types.ValidationError[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.ValidationError[], unknown, Types.ValidationError[]>, 'queryFn'>> = {
};
export function getGetValidationErrorsDefaultOptions() {
  return getValidationErrorsDefaultOptions;
};
export function setGetValidationErrorsDefaultOptions(options: typeof getValidationErrorsDefaultOptions) {
  getValidationErrorsDefaultOptions = options;
}

export function getValidationErrorsQueryKey(curriculumId: number): QueryKey;
export function getValidationErrorsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { curriculumId,  } = params[0] as GetValidationErrorsValidationQueryParameters;

    return trimArrayEnd([
        'ValidationClient',
        'getValidationErrors',
        curriculumId as any,
      ]);
  } else {
    return trimArrayEnd([
        'ValidationClient',
        'getValidationErrors',
        ...params
      ]);
  }
}
export function __getValidationErrors(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getValidationErrors(
      context.queryKey[2] as number,axiosConfig    );
}

export function useGetValidationErrorsQuery<TSelectData = Types.ValidationError[], TError = unknown>(dto: GetValidationErrorsValidationQueryParameters, options?: Omit<UseQueryOptions<Types.ValidationError[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetValidationErrorsQuery<TSelectData = Types.ValidationError[], TError = unknown>(curriculumId: number, options?: Omit<UseQueryOptions<Types.ValidationError[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetValidationErrorsQuery<TSelectData = Types.ValidationError[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.ValidationError[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let curriculumId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ curriculumId,  } = params[0] as GetValidationErrorsValidationQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [curriculumId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.ValidationError[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getValidationErrors(context, axiosConfig) : __getValidationErrors,
    queryKey: getValidationErrorsQueryKey(curriculumId),
    ...getValidationErrorsDefaultOptions as unknown as Omit<UseQueryOptions<Types.ValidationError[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetValidationErrorsData(queryClient: QueryClient, updater: (data: Types.ValidationError[] | undefined) => Types.ValidationError[], curriculumId: number) {
  queryClient.setQueryData(getValidationErrorsQueryKey(curriculumId),
    updater
  );
}

export function setGetValidationErrorsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.ValidationError[] | undefined) => Types.ValidationError[]) {
  queryClient.setQueryData(queryKey, updater);
}